#!/usr/bin/python3

from ftplib import FTP
import sys
import os

def retr(filename, host, user, passwd):
    ftp = FTP(host, user=user, passwd=passwd)
    with open(filename, 'wb') as f:
        try:
            ftp.retrbinary(f"RETR {filename}", f.write)
        except Exception as e:
            print(e)

def upload(path, host, user, passwd):
    ftp = FTP(host, user=user, passwd=passwd)
    filename = os.path.basename(path)
    print(filename)
    try:
        ftp.delete(filename)
    except Exception:
        pass
    finally:
        ftp.storbinary(f"STOR {filename}", open(path, "rb"))

if __name__ == "__main__":
    if sys.argv[1] == "retr" and sys.argv[2] != "" and sys.argv[3] != "" and sys.argv[4] != "" and sys.argv[5] != "":
        retr(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
    elif sys.argv[1] == "upload" and sys.argv[2] != "" and sys.argv[3] != "" and sys.argv[4] != "" and sys.argv[5] != "":
        upload(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])

