#!/usr/bin/python3

from ftplib import FTP
import argparse
import os

def retr(path, host, user, passwd):
    ftp = FTP(host, user=user, passwd=passwd)
    filename = os.path.basename(path)
    with open(filename, 'wb') as f:
        try:
            ftp.retrbinary(f"RETR {path}", f.write)
        except Exception as e:
            print(e)

def upload(path, host, user, passwd):
    ftp = FTP(host, user=user, passwd=passwd)
    filename = os.path.basename(path)
    print(filename)
    try:
        ftp.delete(filename)
    except Exception:
        pass
    finally:
        ftp.storbinary(f"STOR {filename}", open(path, "rb"))

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    
    parser.add_argument("command")
    parser.add_argument("-ho","--host", type=str, required=True)
    parser.add_argument("-u","--user", type=str, required=True)
    parser.add_argument("-p","--passwd", type=str, required=True)
    parser.add_argument("-f","--file", type=str, required=True)

    args = parser.parse_args()


    if args.command == "retr":
        retr(args.file, args.host, args.user, args.passwd)
    elif args.command == "upload":
        upload(args.file, args.host, args.user, args.passwd)

